name = "GlobalGrids"
uuid = "04ffc4db-dae8-4dbd-80c0-66bcb7ba3f11"
version = "1.0.0-DEV"
authors = ["Josh Day <emailjoshday@gmail.com> and contributors"]

[deps]
GeoFormatTypes = "68eda718-8dee-11e9-39e7-89f7f65f511f"
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
GeometryOps = "3251bfac-6a57-4b6d-aa61-ac1fef2975ab"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Proj = "c94c279d-25a6-4763-9509-64d165bea63e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StyledStrings = "f489334b-da3d-4c2e-b8f0-e476e12c162b"

[compat]
GeoFormatTypes = "0.4.4"
GeoInterface = "1.6.0"
GeometryBasics = "0.5.10"
GeometryOps = "0.1.30"
LinearAlgebra = "1.12.0"
Proj = "1.9.0"
StaticArrays = "1.9.15"
StyledStrings = "1.11.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
