[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
DGGS = "1b1208a4-f9dd-4606-8704-9f68bba98fd1"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
YAXArrays = "c21b50f5-aa40-41ea-b809-c0f5e47bfa5c"
