project:
  type: website
  render:
    - "*.qmd"

engines: ['julia']

website:
  title: "GlobalGrids.jl"
  page-navigation: true
  navbar:
    # left:
      # - href: index.qmd
      #   text: Home
    right:
      - icon: github
        href: https://github.com/joshday/GlobalGrids.jl
        aria-label: GitHub
  sidebar:
    style: docked
    search: true
    contents:
      - text: "Intro"
        file: index.qmd
      - h3.qmd
      - coordinates.qmd
      - icosahedron.qmd

format:
  html:
    code-tools:
      source: true
      toggle: false
      caption: none
    theme: flatly
    toc: true
    css: styles.css

execute:
  cache: true
